### ISSUE TITLE
spotify.app.link

### ISSUE THREAD

**Issue by p1r473** [ftpmorph/ftprivacy#13]
This is Spotify's URL shortener domain to take you to the application store download link

**Comment by ftpmorph** [comment]
The reason these are blocked is because they are generated by a third party "analytics" SDK to gather information on the device and user when clicked.

Here's the sales pitch for these "smart deep links" from the company that owns the app.link domain:

> Branch’s deep links store contextual information about where a user wants to go, where the link was clicked, who originally shared the link, and **an almost unlimited amount of custom data.**

https://branch.io/what-is-deep-linking/

The app.link domain is owned by Branch, the company linked above:

https://www.whois.com/whois/app.link

What is Branch?

> Branch Metrics is a deep linking and business **analytics platform** offering developer tools for large and independent mobile application companies. Its toolset contains web, iOS, and Android SDKs which generate **smart deep links that pass data through application install to facilitate and track conversions and user engagement through targeted communications.**

https://en.wikipedia.org/wiki/Branch_Metrics

In other words these are not simply URL shortening domains, but instead are actually used to collect, in the words of the company that provides them, "an almost unlimited amount of custom data."

Blocking these is therefore a privacy win, even if it can be a little inconvenient.

This block notably does not prevent regular App Store or Play Store links from working, and of course does not prevent you from searching for the Spotify app on either yourself, it only blocks a specific type of link designed to collect data about you and your device.

You are of course more and free to whitelist app.link domains on your network or device, but they have a valid privacy reason for being included in the blocklist and the downside only equates to a minor inconvenience, so on balance I consider them as belonging on the list.
